vim9script

# {{{ Plugin management
# Install plug with:
# curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#
#   :PlugInstall to install the plugins
#   :PlugUpdate  to install or update the plugins
#   :PlugDiff    to review the changes from the last update
#   :PlugClean   to remove plugins no longer in the list
call plug#begin()
Plug 'AndrewRadev/sideways.vim'
Plug 'andymass/vim-matchup'
Plug 'azabiong/vim-highlighter'
Plug 'BlueCatMe/TempKeyword'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'dmix/elvish.vim'
Plug 'girishji/easyjump.vim'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'jeetsukumaran/vim-indentwise'
Plug 'jiskattema/new-moon.vim'
Plug 'jiskattema/vim-unicoder'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/vim-easy-align'
Plug 'kkoomen/vim-doge'
Plug 'mattn/emmet-vim'
Plug 'mhinz/vim-signify'
Plug 'michaeljsmith/vim-indent-object'
Plug 'NLKNguyen/papercolor-theme'
Plug 'preservim/tagbar'
Plug 'rafamadriz/friendly-snippets'
Plug 'skywind3000/vim-quickui'
Plug 'tpope/vim-characterize'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/ShowMarks'
Plug 'yegappan/bufselect'
Plug 'yegappan/lsp'
call plug#end()
# }}}

# {{{ Settings
var mapleader = "\\"           # Start my key bindings with \
set nocompatible               # No Vi support
filetype plugin indent on
syntax on
set shell=/usr/bin/sh          # Use something POSIX compattible
set noexrc                     # Disable reading of working directory vimrc files
set belloff=all                # Bells are annoying
set nobackup                   # Backup files
set noundofile
set cryptmethod=blowfish2

set dir=~/.vim/swap,.          # Store swapfiles here
set updatetime=1000            # Certain plugins use this for CursorHold event triggering
set viminfo=%,'50,/50,:50
set viminfofile=.git/viminfo
# }}}

# Tabs, windows and buffers{{{
set hidden                     # Allow hidden buffers
set showtabline=0              # We dont need a tab line
set splitbelow                 # Split below current window
set splitright                 # Split window to the right
set splitkeep=cursor
set fillchars+=vert:│
# }}}

# Theming {{{
set background=dark            # Dark background by default
set termguicolors              # Enable 24-bit color support for terminal Vim
colorscheme new-moon
highligh link LspDiagSignWarningText Wildmenu
set colorcolumn=81,82          # Highlight 81 and 82 columns
set scrolloff=5                # Keep space around the cursor line
set cmdheight=2                # some more space on the bottom

set showcmd                    # Show keypresses in bottom-right
set shortmess=finxToOcImrw

set laststatus=1               # Dont need a statusline for one window
set relativenumber             # Relative numbers
set noruler                    # No ruler with column, row, percentage
set signcolumn=number          # Render signs in the number column

set showmatch                  # show matching brackets
set matchtime=5                # blink matching brackets for 5 tenths of a second
set matchpairs=(:),{:},[:]

set listchars=eol:$,tab:>-,trail:-
# }}}

# {{{ Indenting, whitespace, and wrapping
set formatoptions=qjnlro       # Format options
set autoindent                 # Indented text
set shiftwidth=2               # Default indentation amount
set smarttab                   # Tab at the start of line inserts blanks
set expandtab                  # Use spaces instead of tabs
set tabstop=4                  # Tab width
set nowrap                     # Do not wrap long lines
set breakindent                # Wrap long lines *with* indentation
set textwidth=80               # Standard width before breaking
set breakindentopt=shift:2,min:5,sbr
set showbreak=…
set backspace=indent,eol,start
# }}}

# {{{ Spelling
set spelllang=en,nl            # default to English and Dutch
set thesaurus+=/home/jiska/.vim/thesaurus/english.txt
set dictionary=/usr/share/dict/words
set spelloptions=camel
set keywordprg=:DictPrg
# }}}

# {{{ Completion
set autocomplete
set complete=.,w,b,t
set completeopt=menu,menuone,noinsert,noselect,popup
set pumheight=20               # Height of complete list
set infercase                  # Smart casing when completing
set wildmode=longest:full      # Completion on command line
# }}}

# {{{ Folding and concealing
set conceallevel=0             # Always show text normally
set foldlevelstart=20
set foldmethod=indent          # Simple and fast
# }}}

# {{{ Search
set hlsearch                   # Highlight search results by default
set ignorecase                 # Search in case-insensitively
set smartcase                  # Case-smart searching
set noincsearch                # Dont go to search results immediately
# }}}

# {{{ Paths
set path=.,**/*                # Recursively search subdirectories
set wildignore+=**/env/**      # But dont look in virtualenvs
set wildignore+=**/venv/**
set wildignore+=**/.git/**     #     ...git repos
set wildignore+=**/node_modules/** # ...npm directories
# }}}

# {{{ Functions
def g:StylePrg(): void
  :%y
  new
  normal p
  setlocal nobuflisted
  setlocal buftype=nofile
  setlocal bufhidden=hide
  setlocal noswapfile
  :%!style
enddef

def g:DictPrg(lookup: string): void
  new
  execute 'silent read !dict -d english ' .. lookup
  setlocal nobuflisted
  setlocal buftype=nofile
  setlocal bufhidden=hide
  setlocal noswapfile
  normal gg
enddef
command -nargs=1 DictPrg call DictPrg(<f-args>)

func GitGrep(...)
  var save = &grepprg
  set grepprg=git\ grep\ -n\ $*
  var s = 'grep'
  for i in a:000
    let s = s . ' ' . i
  endfor
  exe s
  let &grepprg = save
endfun
command -nargs=? G call GitGrep(<f-args>)

def Vifm()
  # Get a list of filenames from Vifm
  var tmp = tempname()
  silent execute('silent !vifm --choose-files ' .. tmp)
  var mylist = readfile(tmp)
  call delete(tmp)

  # Vifm probably messed up the display
  redraw!

  # Replace the argument list
  if len(mylist) > 0
    :%argdelete
    for a in mylist
      # add at the end of the current argument list
      execute(":$argadd " .. fnameescape(a))
    endfor

    # Start editing the first file
    first!
  endif
enddef
command Vifm call Vifm()
# }}}

# {{{ Keybindings 
nmap <Leader>d :SignifyDiff!<CR>
nmap <Leader>h :SignifyHunkDiff<CR>
nmap <Leader>s :SignifyToggle<CR>
nmap <Leader>b :TagbarToggle<CR>

nmap <Leader>1 :normal 1gt<CR>
nmap <Leader>2 :normal 2gt<CR>
nmap <Leader>3 :normal 3gt<CR>
nmap <Leader>4 :normal 4gt<CR>
nmap <Leader>5 :normal 5gt<CR>

nmap <silent> <Leader>- :Vifm<CR>
nmap <silent> - :Bufselect<CR>

nmap yoe :set invruler<CR>
nmap yof :if &fo =~ 'a' \| set fo-=at \| else \| set fo+=at \| endif<CR>

nmap <Ins> yop
nmap <Space> <C-w><C-w>
nnoremap Q :q<CR>

# hit leader twice to open menu
noremap <Leader><Leader> :call quickui#menu#open()<cr>

# Scroll other windows using page up and page down
nnoremap <silent> <pageup> <c-w>p<c-y><c-w>w
nnoremap <silent> <pagedown> <c-w>p<c-e><c-w>w
inoremap <silent> <pageup> <C-[><c-w>p<c-y><c-w>wgi
inoremap <silent> <pagedown> <C-[><c-w>p<c-e><c-w>wgi

# Close the preview window from insert mode
inoremap <C-z> <C-o>:pclose<CR>

# vsnip: Jump forward or backward
inoremap <expr>   <Tab> pumvisible() ? "\<C-n>" : vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<Tab>'
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : vsnip#jumpable(-1)  ? '<Plug>(snip-jump-prev)' : '<S-Tab>'
imap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'

# matchup
nmap <Leader>? :MatchupWhereAmI?<CR>

# vim-which-key

# vim-highlighter
nmap [h :Hi {<CR>
nmap ]h :Hi }<CR>
nmap [H :Hi <<CR>
nmap ]H :Hi ><CR>
# }}}

# {{{ Configure plugins

packadd! cfilter

# ShowMarks
g:showmarks_enable = 0
g:showmarks_include = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

## ignore help, quickfix, non-modifiable buffers
g:showmarks_ignore_type = "h"

## hilight lower & upper marks
g:showmarks_hlline_lower = 1
g:showmarks_hlline_upper = 1 


# Signify
var signify_disable_by_default = 0


# Sideways
nnoremap <Esc>h :SidewaysLeft<cr>
nnoremap <Esc>l :SidewaysRight<cr>

nmap <Esc>m <Plug>SidewaysArgumentInsertFirst
nmap <Esc>, <Plug>SidewaysArgumentInsertBefore
nmap <Esc>. <Plug>SidewaysArgumentAppendAfter
nmap <Esc>/ <Plug>SidewaysArgumentAppendLast

omap aa <Plug>SidewaysArgumentTextobjA
xmap aa <Plug>SidewaysArgumentTextobjA
omap ia <Plug>SidewaysArgumentTextobjI
xmap ia <Plug>SidewaysArgumentTextobjI


# vim-lsp
var lspOpts = {
      autoComplete: false,
      omniComplete: true,
      ignoreMissingServer: true,
      completionMatcher: 'case',
      showDiagOnStatusLine: true,
      showDiagInPopup: false,
      showSignature: true,
      echoSignature: false,
      showInlayHints: false,
      hoverInPreview: true,
      diagSignWarningText: '> ',
      diagSignInfoText: '- ',
      diagSignHintText: '+ ',
      diagSignErrorText: '>>',
      diagVirtualTextAlign: 'above',
      highlightDiagInline: false,
      ultisnipsSupport: false,
      vsnipSupport: true,
      snippetSupport: true,
      }
autocmd User LspSetup call LspOptionsSet(lspOpts)

var lspServers = [
      {
        name: 'golang',
        filetype: ['go', 'gomod'],
        path: '/usr/bin/gopls',
        args: ['serve'],
        syncInit: true
      },
      {
        name: 'python',
        filetype: ['python'],
        path: 'pylsp',
        args: []
      },
      # {
      #   name: 'shell',
      #   filetype: ['sh'],
      #   path: '/home/jiska/.local/bin/bash-lsp.sh',
      #   args: []
      # },
      # {
      #   name: 'Languagetool',
      #   filetype: ['text', 'markdown'],
      #   path: '/home/jiska/Code/ltex-ls/ltex-ls-16.0.0/bin/ltex-ls',
      #   args: [],
      #   syncInit: true
      # }
      ]
autocmd User LspSetup call LspAddServer(lspServers)

nnoremap <Esc>D <Cmd>LspGotoDefinition<CR>
nnoremap <Esc>I <Cmd>LspGotoImpl<CR>
nnoremap <Esc>T <Cmd>LspGotoTypeDef<CR>

nnoremap <Esc>d <Cmd>topleft LspPeekDefinition<CR>
nnoremap <Esc>i <Cmd>topleft LspPeekImpl<CR>
nnoremap <Esc>t <Cmd>topleft LspPeekTypeDef<CR>

nnoremap <Esc>s <Cmd>LspDocumentSymbol<CR>
nnoremap <Esc>r <Cmd>LspShowReferences<CR>

nnoremap <Esc>o<Esc>o <Cmd>call LspOptionsSet(#{hoverInPreview: v:false})<bar>LspHover<CR>
nnoremap <Esc>oo      <Cmd>call LspOptionsSet(#{hoverInPreview: v:true })<bar>LspHover<CR>

nnoremap <Esc>e <Cmd>LspDiagShow<CR>

nnoremap [V <Cmd>LspDiagFirst<CR>
nnoremap [v <Cmd>LspDiagPrev<CR>
nnoremap ]v <Cmd>LspDiagNext<CR>
nnoremap ]V <Cmd>LspDiagLast<CR>

autocmd User LspAttached setlocal tagfunc=lsp#lsp#TagFunc
# }}}

# {{{ Autocommands
augroup tmux_clipboard
  autocmd!
  autocmd TextYankPost * if len(@") > 3 | call system("tmux load-buffer -", @") | endif
augroup END

# TODO: how to tell if the window contains a quickfix and location list?
augroup QuickFixHistory
  autocmd!
  autocmd BufWinEnter quickfix nnoremap <buffer> - <Cmd>colder<CR>
  autocmd BufWinEnter quickfix nnoremap <buffer> - <Cmd>lolder<CR>
augroup END

# Always wrap long lines in preview windows.
autocmd BufEnter * if &previewwindow | set wrap | endif
# }}}

#{{{ Quick menu

quickui#menu#reset()
g:quickui_border_style = 2
g:quickui_color_scheme = 'papercol_dark'

# items containing tips, tips will display in the cmdline
call quickui#menu#install('&Plugins', [
   [ "&Signify toggle\t\\s", 'SignifyToggle', 'Show linechanges in the gutter' ],
   [ "&Diff file\t\\d", 'SignifyDiff', 'Show diff in diff mode' ],
   [ "Diff &hunk\t\\h", 'SignifyHunkDiff', 'Show diff in a popup' ],
   ['--', '', '' ],
   ['Text stat&istics', 'call StylePrg()', 'runs GNU style on the current buffer' ],
   ['&Limelight', 'Limelight!!', 'Toggle limelight' ],
   ['&Unicoder', 'Unicoder', 'Use abbreviations to insert unicode characters'],
   ['Show &Marks', 'ShowMarksToggle', 'Highlight marks'],
   ['Tag&bar', 'TagbarToggle', 'Toggle tagbar' ],
   ['&Emmet', 'packadd emmet-vim', 'Enable emmet'],
   ])

# script inside %{...} will be evaluated and expanded in the string
call quickui#menu#install("&Options", [
   [ "&Paste\tyop", 'set invpaste'],
   [ "&Wrap\tyow", 'execute "normal yow"' ],
   [ "&Cursorline\tyoc", 'execute "normal yoc"' ],
   [ "C&ursorcolumn\tyou", 'execute "normal you"' ],
   [ "&Xrosshairs\tyox", 'execute "normal yox"' ],
   [ "&Background\tyob", 'execute "normal yob"' ],
   [ "&Hlsearch\tyoh", 'execute "normal yoh"' ],
   [ "&Ignorecase\tyoi", 'execute "normal yoi"' ],
   [ "&Diff\tyod", 'execute "normal yod"' ],
   [ "&List\tyol", 'execute "normal yol"' ],
   [ "&Number\tyon", 'execute "normal yon"' ],
   [ "&Relativenumber\tyor", 'execute "normal yor"' ],
   [ "&Spell\tyos", 'execute "normal yos"' ],
   [ "&Virtualedit\tyov", 'execute "normal yov"' ],
   [ "Rul&er\tyoe", 'set invruler' ],
   [ "\Auto format\tyof", "if &fo =~ 't' | set fo-=t | else | set fo+=t | endif"],
   [ "All options", 'options' ],
   ])

call quickui#menu#install("&LSP", [
   [ "Goto definition\t<M-D>" ],
   [ "Goto implementation\t<M-I>" ],
   [ "Goto type definition\t<M-T>" ],
   [ "---" ],
   [ "Find document symbol\t<M-s>" ],
   [ "Find references\t<M-r>" ],
   [ "Documentation\t<M-o>" ],
   [ "---" ],
   [ "Show diag.\t<M-e>" ],
   ])

# register HELP menu with weight 10000
call quickui#menu#install('H&elp', [
   ["&Cheatsheet", 'help index', ''],
   ['T&ips', 'help tips', ''],
   ['--', ''],
   ["&Tutorial", 'help tutor', ''],
   ['Quick &reference', 'help quickref', ''],
   ['&Summary', 'help summary', ''],
   ], 10000)

# }}}

# {{{ Legacy
# Make modified arrow keys (<C-Left> etc.) work in alacritty 
# execute "set <xUp>=\<Esc>[@;*A"
# execute "set <xDown>=\<Esc>[@;*B"
# execute "set <xRight>=\<Esc>[@;*C"
# execute "set <xLeft>=\<Esc>[@;*D"

# Escape sequence to get proper colors
# execute "set t_8f=\e[38;2;%lu;%lu;%lum"
# execute "set t_8b=\e[48;2;%lu;%lu;%lum"

# Navigate the jumplist with <M-i> instead of <C-i> which is Tab.
# I've configured my terminal to send <M-i> for when i press <C-i>
#nnoremap i <C-i>


# Try using Kitty keyboard protocol
# set kpc=alacritty:kitty
# }}}

# Easy insertion of emojis with C-K
execute 'digraph :x 128544'
execute 'digraph :) 128578'
execute 'digraph :D 128512'
execute 'digraph =D 128513'
execute 'digraph :P 128523'
execute 'digraph :\| 128528'
execute 'digraph =\| 128529'
execute 'digraph :O 128558'
execute 'digraph :/ 128533'
execute 'digraph :( 128577'
execute 'digraph =( 128543'
execute 'digraph :E 128556'
execute 'digraph /\ 128591'
# vim: fdm=marker foldlevel=0 fileencoding=utf-8
